In [ ]:
%pip install fg-data-profiling
%pip install plotly 
%pip install numpy

# Does Sponsoring IG Posts Matter....?

---

# Section 1:  What are we working with? 
- Wtf are we looking at? 
- what are the cols and their meanings.
- how big is the data [bonus points for MB size / RAM space]
- is the data clean (dupes or nans?)
- how do we clean it?


------ 

# Section 2:  Who is this data. 
- How many users are in this dataset? 
- How many posts?  
- Who posts the most? 
- Most popular user. 
- Most popular post.



-----
# Section 3:  Describe me the data.
- What is the averge users number of followers? 
- What's the best way to describe that? 
- Which type of distribution does each followers, likes, and comments follow? 
- What the avarege users comment/like per post..  
- What the most common users comment/like per post.. 
- Is there a relationship between  commets/likes/followers?
- What the average users experience? 
- What is something that stands out to you? 

------


# Section 4: Show me the money.
- Does sponsoring a post actually up engagment? 
- If sponsoring a post costs $100 bucks, is it worth it?
- Is there something that stands out about people that were chosen to be sponsored vs people that were not.


Ratio of engagement to number of followers -> compare to sponsored vs non-sponsored
What’s the ratio I need in order to get a sponsorship? 
Is it worth it to buy bots to get sponsored?
What’s the average follower count of sponsored vs non-sponsored people? (that’s your null hypothesis)
Who sampled this data?
Does sponsor type correlate with user follower? - correlate might be wrong word
Plot followers vs unsponsored

-----
-----
-----

# START:: Section 1 - WTF we working with here?

- load the data
- what are the cols and their meanings.
- how big is the data [bonus points for MB size / RAM space]
- is the data clean (dupes or nans?)
- how do we clean it?

## Load the data

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

from data_profiling import ProfileReport

In [2]:
df_un = pd.read_csv('zenodo-data/unsponsored_posts.csv')
df_un['sponsor_type'] = 'Unsponsored'
print(df_un.shape)
df_un.head()

(28779, 6)

,user_id,user_followers,likes,comments,id,sponsor_type
0,8507712693,578.0,5,0,2298140219715003981,Unsponsored
1,5528398196,232.0,2,0,2298141500462471745,Unsponsored
2,1411215703,2081.0,12,1,2298141328454108228,Unsponsored
3,33913737636,1.0,1,0,2298141191417405733,Unsponsored
4,1931824622,3581.0,1,0,2298140745427411928,Unsponsored

In [ ]:
df_sponsored = pd.read_csv('zenodo-data/sponsored_posts.csv')
df_sponsored['sponsor_type'] = 'Sponsored'
print(df_sponsored.shape)
df_sponsored.head()

(29425, 6)

,user_id,user_followers,likes,comments,id,sponsor_type
0,179037181,1634.0,81,5,2297742899655135745,Sponsored
1,25783801241,95.0,3,1,2297738413553416176,Sponsored
2,32030939764,526.0,8,0,2297715524791715348,Sponsored
3,14288521,75570.0,419,17,2297709946912814555,Sponsored
4,2025150409,149.0,2,0,2297705923349356813,Sponsored

## HOW BIG IS THE DATA?

In [4]:
df_un.shape, df_sponsored.shape

((28779, 6), (29425, 6))

## Cleaning the data

In [5]:
# Lets join them together. 

## Okay, lets join them into one dataframe, 
## and then we can do some analysis on the combined dataset.
df = pd.concat([df_un, df_sponsored], ignore_index=True, sort=False)

# Mention the index trap, and how to avoid it. # (appending/concatenating two dfs will defaul index duplicate indicies)  # dont spend any time on it tho, you can avoid by includeing the ignore_index=True parameter in the concat function, which we did above.
print(df_un.shape, df_sponsored.shape, df.shape)

(28779, 6) (29425, 6) (58204, 6)

In [6]:
# CHECK FOR DUPES
df.duplicated().sum()

np.int64(0)

In [7]:
# CHECK FOR NULLS
df.isnull().sum()

# Is null just meaning 0 or does 0 mean 0 and null means None?

user_id             0
user_followers    364
likes               0
comments            0
id                  0
sponsor_type        0
dtype: int64

In [8]:
# Looking at just the rows that have null values.

# There are 364 Nulls in user_followers.  Let's see what those rows look like.
df[df.isnull()['user_followers']]

,user_id,user_followers,likes,comments,id,sponsor_type
120,34090527093,NaN,0,0,2298143758348114938,Unsponsored
243,33994602264,NaN,1,0,2298139497001137920,Unsponsored
303,174079951,NaN,0,0,2298143821128586138,Unsponsored
662,8426176684,NaN,8,0,2298144505553873944,Unsponsored
663,5817719798,NaN,1,0,2298140344686880783,Unsponsored
...,...,...,...,...,...,...
57004,33210396128,NaN,31,1,2298232290685512980,Sponsored
57799,349778480,NaN,4276,17,2296531793184390220,Sponsored
57822,349778480,NaN,193,2,2295908370988938416,Sponsored
57836,5711493507,NaN,0,0,2299490563714295393,Sponsored
57879,34413541521,NaN,8,0,2299477972153001239,Sponsored

In [9]:
# CHecking to see if there are posts that have 0 and not Null in them
# is NaN the same as 0?
df[df.user_followers < 1]

,user_id,user_followers,likes,comments,id,sponsor_type
180,33982169772,0.0,7,0,2298143013891605157,Unsponsored
783,34211268959,0.0,2,0,2298110647160537407,Unsponsored
1329,11588048260,0.0,4,0,2298144571934545683,Unsponsored
1513,34597595538,0.0,0,0,2297752405163114832,Unsponsored
1753,34394698759,0.0,2,0,2297771940646771993,Unsponsored
...,...,...,...,...,...,...
55697,34430826169,0.0,0,0,2298719645974649910,Sponsored
57090,33156788158,0.0,0,0,2298211078110462230,Sponsored
57549,32074468485,0.0,0,0,2297893168296105165,Sponsored
57550,34803506130,0.0,6,1,2297893141577031144,Sponsored
57693,33292878338,0.0,0,0,2297792544738112112,Sponsored

In [10]:
# sanity check, seeing if a null id is present the the 0 values.  it is not. lets drop and continue. 
id_with_nan = 2298140344686880783
df_nulls = df[df.user_followers < 1]

df_nulls[df_nulls['id'] == id_with_nan]

Empty DataFrame
Columns: [user_id, user_followers, likes, comments, id, sponsor_type]
Index: []

In [11]:
# no they are different, lets just drop them as the seem like mistakes and less than 1% of the data. 
print(df.shape)
df = df.dropna(subset=['user_followers'])
df.shape

(58204, 6)

(57840, 6)

## A little sneaky way to insepct all this data easily.

In [12]:
## This is helpful for inspecting the data. Outliers. Etc...
profile = ProfileReport(df, title="Sponsored vs Un-Sponsored Posts")
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 6/6 [00:00<00:00, 190.28it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

# Section 2:  Who is the data? 
- How many users are in this dataset? 
- How many posts?  
- Who posts the most? 
- Most popular user. 
- Top 5 most popular users. 
- Most popular post.

## How many users are there?
_are you sure..?_

In [13]:
print(len(df))

# df.nunique() / df.shape[0]       ## <-- shows % of unique values in each column.  
df.nunique()

57840

user_id           39880
user_followers    12082
likes              2577
comments            529
id                57840
sponsor_type          2
dtype: int64

In [14]:
# Enter answer here...
answer_how_many_users = None

## How many posts?

In [15]:
df.duplicated(subset='id').sum()

np.int64(0)

In [16]:
# Enter answer here...
answer_how_many_posts = None

## Who posts the most? and how many times did they post?

In [17]:
df.user_id.value_counts().head(10)

user_id
189726411      317
33156788158    201
32103598145    188
1777222954     176
29046900081    112
33136787582    109
9133990278     105
4733306056     103
8909551676      91
11312497392     90
Name: count, dtype: int64

In [18]:
ANSWER_who_posts_the_most = None
ANSWER_how_many_they_posted = None

## Who is the most popular user?

In [19]:
ANSWER_most_popular_user = None  #PUT ANSWER HERE
df.sort_values(by='user_followers', ascending=False).head(10)

,user_id,user_followers,likes,comments,id,sponsor_type
35913,980505357,22461425.0,26184,261,2295300871225781060,Sponsored
49173,980505357,22461425.0,9763,194,2289594235479829478,Sponsored
29946,980505357,22461425.0,27767,955,2297657202750273946,Sponsored
32504,980505357,22461425.0,5128,223,2296768647979255059,Sponsored
55316,980505357,22461425.0,19555,363,2298851123035866429,Sponsored
38950,980505357,22461425.0,20741,346,2293996795263333144,Sponsored
52846,980505357,22461425.0,18665,286,2288144857007273371,Sponsored
49499,980505357,22461425.0,49250,320,2289502620706877174,Sponsored
36101,980505357,22461425.0,9053,675,2295233905421023902,Sponsored
46236,980505357,22461425.0,36277,472,2291134761194587811,Sponsored

### Who are the top 5 most popular users?

In [20]:
sorted_followers = df.sort_values(by='user_followers', ascending=False)
sorted_followers.drop_duplicates(subset=['user_id'], keep='first').head(5)

,user_id,user_followers,likes,comments,id,sponsor_type
35913,980505357,22461425.0,26184,261,2295300871225781060,Sponsored
54645,9232256,22355537.0,69832,1137,2299030933376079639,Sponsored
49682,304358009,14150875.0,1448420,16336,2289456833311836907,Sponsored
36758,49069741,10338808.0,59989,295,2294949523002376534,Sponsored
56901,3240707830,7816822.0,10087,919,2298260276013035594,Sponsored

In [21]:
ANSWER_top_five_popular_users = sorted_followers.drop_duplicates(subset=['user_id'], keep='first').head(5)['user_id'].values
ANSWER_top_five_popular_users

array([ 980505357,    9232256,  304358009,   49069741, 3240707830])

## What post is the most popular?

In [22]:
## Do we need to do this group by?
gb_id = df.groupby(by='id')['likes'].sum().sort_values(ascending=False)
gb_id.sort_values(ascending=False).head()

id
2289456833311836907    1448420
2293315178509194025     156299
2289509281069540554     154284
2298260850372723539     142861
2288287996816898557     117191
Name: likes, dtype: int64

In [23]:
df.sort_values(by='likes', ascending=False).head()

,user_id,user_followers,likes,comments,id,sponsor_type
49682,304358009,14150875.0,1448420,16336,2289456833311836907,Sponsored
40805,980505357,22461425.0,156299,2264,2293315178509194025,Sponsored
48041,1699305640,2507408.0,154284,2040,2289509281069540554,Sponsored
56898,10470851,1371999.0,142861,3319,2298260850372723539,Sponsored
52450,980505357,22461425.0,117191,900,2288287996816898557,Sponsored

# Section 3:  Describe me the data.... or Setting the Stage... Or exploring the story... 

- Explore with `df.describe()`
- How many followers does our average user have?
- What's the best way the average users profile and posts?
- Which type of distribution does each followers, likes, and comments follow? 
- What the avarege users comment/like per post..  
- What the most common users comment/like per post.. 
- Is there a relationship between  commets/likes/followers?

- What the average users experience? 
- What is something that stands out to you?

### Explore with `df.describe()`

In [24]:
# How many followers does the average user have?
### This prints super ugly, but it is correct.  We will fix the formatting in a later cell.
df.describe()

            user_id  user_followers         likes      comments            id
count  5.784000e+04    5.784000e+04  5.784000e+04  57840.000000  5.784000e+04
mean   1.035925e+10    2.817048e+04  3.004365e+02     15.912656  2.283678e+18
std    1.159457e+10    4.983031e+05  6.482685e+03    245.320767  8.761804e+16
min    6.696000e+03    0.000000e+00  0.000000e+00      0.000000  3.543554e+17
25%    1.404863e+09    2.400000e+02  6.000000e+00      0.000000  2.292555e+18
50%    5.617494e+09    1.005000e+03  2.300000e+01      1.000000  2.297211e+18
75%    1.642593e+10    4.381750e+03  9.900000e+01      6.000000  2.298142e+18
max    3.483338e+10    2.246142e+07  1.448420e+06  36817.000000  2.299570e+18

In [25]:
## THIS LINE MAKES THE FORMAT PRETTY :) 
pd.options.display.float_format = "{:,.2f}".format
# See the difference from above.
df.describe()

,user_id,user_followers,likes,comments,id
count,"57,840.00","57,840.00","57,840.00","57,840.00","57,840.00"
mean,"10,359,245,026.22","28,170.48",300.44,15.91,"2,283,678,032,019,268,864.00"
std,"11,594,567,321.89","498,303.07","6,482.68",245.32,"87,618,037,877,495,920.00"
min,"6,696.00",0.00,0.00,0.00,"354,355,426,648,860,288.00"
25%,"1,404,863,162.25",240.00,6.00,0.00,"2,292,555,294,610,388,736.00"
50%,"5,617,493,577.00","1,005.00",23.00,1.00,"2,297,210,527,813,451,520.00"
75%,"16,425,931,378.00","4,381.75",99.00,6.00,"2,298,142,193,839,473,408.00"
max,"34,833,376,869.00","22,461,425.00","1,448,420.00","36,817.00","2,299,569,591,382,087,680.00"

### How many followers, likes, comments does our average user have?

In [26]:
### How many followers, likes, comments does our average user have?
metrics = ['user_followers', 'likes', 'comments']


### Is this correct?  <-- Thing about it. 
df[metrics].agg(['mean']).T

                    mean
user_followers 28,170.48
likes             300.44
comments           15.91

#### ANSWER TO: How many followers, likes, comments does our average user have?

```
mean
user_followers	28,170.48
likes	        300.44
comments	15.91
```

Incorrect for 2 reasons.  
1. remember, we have many duplicate users in our database.  they will be throwing off this average.  
2. well. for highly skewed data, you should median and mode are better descriptors than average.

In [27]:
unique_users_df = df.drop_duplicates(subset=['user_id'])
print(df.shape, unique_users_df.shape)


metrics = ['user_followers', 'likes', 'comments']
unique_users_df[metrics].agg(['mean', 'median'])

(57840, 6) (39880, 6)

        user_followers  likes  comments
mean         16,183.52 279.60     15.63
median          885.00  21.00      1.00

QUESTIONS TO ASK IN CLASS
1. Someome tell me why the median of unique users still might be incorrect.  think about the sample of this data...
1. Why would one post with like 1 Billion views mess up the average?

## Which type of distribution is user_followers counts?  
- the too mmuch data in chart to even see it is skewed.  
- log_y axis is much different than plotting the np.log of the values. 
- And why does the first chart suck?

- Which type of distribution does each followers, likes, and comments follow? 
- What the avarege users comment/like per post..  
- What the most common users comment/like per post.. 
- Is there a relationship between  commets/likes/followers?

In [ ]:
## Just showing what a smaple of 1% would look like. Its just easier to comceptualize. 
df_small = df.sample(frac=0.01, random_state=42)  # Take a random sample of 10% of the data for plotting
df_small.shape
fig = px.histogram(df_small['user_followers'], title="User Followers Distribution", log_y=True)
fig.show()

## How would we see the difference between the number of user followers for sponsored and unsponsored posts?

In [26]:
### Remember this from above... 
metrics = ['user_followers', 'likes', 'comments']
unique_users_df[metrics].agg(['mean', 'median']).T

                    mean  median
user_followers 16,183.52  885.00
likes             279.60   21.00
comments           15.63    1.00

In [27]:
# Group by the sponsor type and describe them seperately. 
unique_users_df.groupby('sponsor_type')[metrics].agg(['mean', 'median']).reset_index()

  sponsor_type user_followers           likes        comments
                         mean   median   mean median     mean median
0    Sponsored      31,746.17 2,463.00 596.09  85.00    33.61   5.00
1  Unsponsored       5,139.02   457.00  54.99  10.00     2.87   0.00

## Visualize user_followers distribution differences

In [35]:
# Cool lets plot it and see what the distrubtion looks like....

import plotly.express as px
fig = px.histogram(df['user_followers'], title="User Followers Distribution")
fig.show()

## Log the y_axis, 
fig = px.histogram(df['user_followers'], title="User Followers Distribution", log_y=True)
fig.show()

In [ ]:
types_followers_medians = df.groupby('sponsor_type')['user_followers'].median()
types_followers_medians = pd.DataFrame(types_followers_medians).reset_index()
px.bar(types_followers_medians, x='sponsor_type', y='user_followers')

## Box plot showing the Quartiles.  
25% of users live in each box.

In [29]:
fig = px.box(
    unique_users_df,
    y="user_followers",
    points='all',
    title="Distribution of Instagram User Followers, RAW log_y=False",
)

fig.show()



fig = px.box(
    unique_users_df,
    y="user_followers",
    points='all',
    title="Distribution of Instagram User Followers, log_y=True",
    log_y=True
)
fig.show()



unique_users_df["followers_log"] = np.log10(unique_users_df["user_followers"] + 1)

fig = px.box(
    unique_users_df,
    y="followers_log",
    points="all",
    title="Instagram Follower Counts (log10 + 1)"
)

fig.show()


fig = px.box(
    unique_users_df,
    y="user_followers",
    points=False,
    title="Instagram Follower Counts, RAW, not logged just limiting Rage [0,10000]"
)

fig.update_yaxes(range=[0, 10000])

fig.show()

/var/folders/yb/hf5hzk391w9157dctx7yzyn80000gn/T/ipykernel_90859/3473216225.py:23: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

## Showing how Quantiles work.  that 25% of rows will be in each quartile.

In [31]:
print(unique_users_df[metrics[0]].describe())
unique_users_df[unique_users_df['user_followers'] >= 3749].shape[0] / unique_users_df.shape[0]

count       39,880.00
mean        16,183.52
std        214,541.93
min              0.00
25%            222.75
50%            885.00
75%          3,749.00
max     22,461,425.00
Name: user_followers, dtype: float64

0.25005015045135404

In [32]:
# A better way to show that 25% of the rows are in each quantile
unique_users_df['user_followers_quantile'] = pd.qcut(unique_users_df['user_followers'], q=4, labels=['q1', 'q2', 'q3', 'q4'])
unique_users_df['user_followers_quantile'].value_counts()

/var/folders/yb/hf5hzk391w9157dctx7yzyn80000gn/T/ipykernel_90859/2846836264.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

user_followers_quantile
q2    9977
q1    9970
q4    9969
q3    9964
Name: count, dtype: int64